# ===============================
# SERVIDOR
# ===============================
server.port=8080
spring.application.name=EscolaGerenciamentoDeAulas

# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:postgresql://ep-cold-pine-axkrxua6.c-4.us-east-2.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=${database_key}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
